HOST = 0.0.0.0
API_PORT = 5001

export FLASK_APP = $(PWD)/app.py
export FLASK_ENV=development

# Python env
PYTHON_VERSION ?= python
VENV = $(PWD)/.venv
PYTHON = $(VENV)/bin/python
PIP = $(VENV)/bin/pip
FLASK = $(VENV)/bin/flask
BLACK = $(VENV)/bin/black
